// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.1
// source: proto/req.proto

package req

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type PhraseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Place  int32  `protobuf:"varint,2,opt,name=place,proto3" json:"place,omitempty"`
	OldMMR int32  `protobuf:"varint,3,opt,name=oldMMR,proto3" json:"oldMMR,omitempty"`
	NewMMR int32  `protobuf:"varint,4,opt,name=newMMR,proto3" json:"newMMR,omitempty"`
}

func (x *PhraseRequest) Reset() {
	*x = PhraseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_req_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PhraseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhraseRequest) ProtoMessage() {}

func (x *PhraseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_req_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhraseRequest.ProtoReflect.Descriptor instead.
func (*PhraseRequest) Descriptor() ([]byte, []int) {
	return file_proto_req_proto_rawDescGZIP(), []int{0}
}

func (x *PhraseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PhraseRequest) GetPlace() int32 {
	if x != nil {
		return x.Place
	}
	return 0
}

func (x *PhraseRequest) GetOldMMR() int32 {
	if x != nil {
		return x.OldMMR
	}
	return 0
}

func (x *PhraseRequest) GetNewMMR() int32 {
	if x != nil {
		return x.NewMMR
	}
	return 0
}

// The response message containing the greetings
type PhraseReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *PhraseReply) Reset() {
	*x = PhraseReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_req_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PhraseReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhraseReply) ProtoMessage() {}

func (x *PhraseReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_req_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhraseReply.ProtoReflect.Descriptor instead.
func (*PhraseReply) Descriptor() ([]byte, []int) {
	return file_proto_req_proto_rawDescGZIP(), []int{1}
}

func (x *PhraseReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_req_proto protoreflect.FileDescriptor

var file_proto_req_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x71, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0f, 0x62, 0x61, 0x64, 0x5f, 0x6d, 0x73, 0x67, 0x5f, 0x68, 0x61, 0x6e, 0x64, 0x6c,
	0x65, 0x72, 0x22, 0x69, 0x0a, 0x0d, 0x70, 0x68, 0x72, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x6c, 0x61, 0x63, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x6f, 0x6c, 0x64, 0x4d, 0x4d, 0x52, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f,
	0x6c, 0x64, 0x4d, 0x4d, 0x52, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x65, 0x77, 0x4d, 0x4d, 0x52, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x65, 0x77, 0x4d, 0x4d, 0x52, 0x22, 0x27, 0x0a,
	0x0b, 0x70, 0x68, 0x72, 0x61, 0x73, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x5d, 0x0a, 0x0e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x12, 0x4b, 0x0a, 0x09, 0x67, 0x65, 0x74, 0x50,
	0x68, 0x72, 0x61, 0x73, 0x65, 0x12, 0x1e, 0x2e, 0x62, 0x61, 0x64, 0x5f, 0x6d, 0x73, 0x67, 0x5f,
	0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x2e, 0x70, 0x68, 0x72, 0x61, 0x73, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x62, 0x61, 0x64, 0x5f, 0x6d, 0x73, 0x67, 0x5f,
	0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x2e, 0x70, 0x68, 0x72, 0x61, 0x73, 0x65, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x6b, 0x6f, 0x6c, 0x63, 0x68, 0x75, 0x72, 0x69, 0x6e, 0x2f, 0x62,
	0x61, 0x64, 0x5f, 0x6d, 0x73, 0x67, 0x5f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x71, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_req_proto_rawDescOnce sync.Once
	file_proto_req_proto_rawDescData = file_proto_req_proto_rawDesc
)

func file_proto_req_proto_rawDescGZIP() []byte {
	file_proto_req_proto_rawDescOnce.Do(func() {
		file_proto_req_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_req_proto_rawDescData)
	})
	return file_proto_req_proto_rawDescData
}

var file_proto_req_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_req_proto_goTypes = []interface{}{
	(*PhraseRequest)(nil), // 0: bad_msg_handler.phraseRequest
	(*PhraseReply)(nil),   // 1: bad_msg_handler.phraseReply
}
var file_proto_req_proto_depIdxs = []int32{
	0, // 0: bad_msg_handler.MessageHandler.getPhrase:input_type -> bad_msg_handler.phraseRequest
	1, // 1: bad_msg_handler.MessageHandler.getPhrase:output_type -> bad_msg_handler.phraseReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_req_proto_init() }
func file_proto_req_proto_init() {
	if File_proto_req_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_req_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PhraseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_req_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PhraseReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_req_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_req_proto_goTypes,
		DependencyIndexes: file_proto_req_proto_depIdxs,
		MessageInfos:      file_proto_req_proto_msgTypes,
	}.Build()
	File_proto_req_proto = out.File
	file_proto_req_proto_rawDesc = nil
	file_proto_req_proto_goTypes = nil
	file_proto_req_proto_depIdxs = nil
}
